Fix panic when subtracting "now" Instant
Similar to the problem reported in #27, which was fixed in f91a3d4, I saw this
error:

```
thread 'main' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292:17
```
(sorry, no backtrace)

Since I am using the music block with text rotation, I am best-guessing that the
error is caused by the Instant subtraction in rotatingtext widget.